---
title: "Project Team"
comments: false
---

# Adam M. Wilson, PI
Coordination and management of research activities at the University at Buffalo. This includes: 1) networking with relevant parties to define field campaign objectives in South Africa and the U.S., 2) collaborating with John Silander at the University of Connecticut on this and other aspects of the project, and 3) preliminary analyses of available remote sensing products across the region. Wilson will also manage a postdoc (to be named).

# Postdoc (to be named)
Networking with stakeholders and development of technical needs for field campaign.

# John Silander, Co-I
Coordination and management of research activities at the University of Connecticut. This includes: 1) assembling datasets relevant to assessing and monitoring biodiversity in South Africa, such as relevé and other species inventory data, digital species occurrence data, species trait data, and lists of key biodiversity professionals in South Africa, 2) collaborating with Adam Wilson at the University at Buffalo on this and other aspects of the project, and 3) preliminary analyses of plant species reflectance data, how these may vary across the landscape, and how these relate to other measured plant traits. Silander will manage a graduate student, Henry Frye, to assist in the assembling of relevant databases and conducting the preliminary analyses as outlined above.

# Cory Merow, professional consultant
Developing modelling protocols for integrating plant demographic models with remotely sensed lidar height estimates and Developing modelling protocols for integrating plant demographic models with remotely sensed lidar height estimates and analysis of leaf spectra.

# Henry Frye, PhD Student
 
Full literature review for hyperspectral / lidar remote sensing of shrubland and arid ecosystems with contributions to field campaign proposal.